# extras/kitty/vinedunes.conf
## name: ayu
foreground #AD9E86
background #181818


color0 #F07178
color1 #FFEE99
color2 #E7C547
color2 #2E7465 
# color3 #0D0013 
color4 #B8CC52
color4 #FFB454
color5 #E6B673
color6 #FF7733
color7 #C73C20 
color8 #C99619 
color9 #A8FF4A 
color10  #9D62D3 
color12 #193F0C 
color13  #515C1B 
color14 #455153

# Cursor
cursor                   #FF0000
# cursor                   #09E717
# cursor_text_color        #000000

# Borders (panes)
active_border_color      #D06666
inactive_border_color    #514742

# Tabs
active_tab_foreground    #000000
active_tab_background    #F0E68C
inactive_tab_foreground  #3A4A50
inactive_tab_background  #080808

# font_family    UbuntuMono Nerd Font 
font_family      Hurmit Nerd Font Mono Light
# font_family      ZedMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
enable_audio_bell no
cursor_shape block
cursor_underline_thickness 3.0
disable_ligatures always

# modify_font cell_width 105%
modify_font cell_width 95%
# modify_font cell_height -0.8px
modify_font cell_height 1px
# modify_font baseline -0.9

# Reload kitty.conf
map ctrl+shift+0 load_config_file
tab_bar_edge top
confirm_os_window_close 0

