## name: crusx-paper

confirm_os_window_close     0
# disable_ligatures           always
enable_audio_bell           no
foreground #AD9E86
background #181818

#Colors
color0   #bbc2cf
color1   #008080
color2   #458F2C
color3   #B8CC52
color4   #E6B673
color5   #FF7733
color6   #FFB454
color7   #A8FF4A
color8   #9D62D3
color9   #C73C20

#Cursor
cursor                       #FF0000
cursor_text_color            #000000
cursor_shape                 block

font_size            11.5
font_family          SeriousShanns Nerd Font Light
italic_font          auto
bold_italic_font     auto

modify_font cell_width     100%
modify_font cell_height    0.8px
modify_font baseline       -1px

# Reload kitty.conf
map ctrl+shift+0 load_config_file


