[ids]

*

[main]
# Remaps the capslock key to escape vise visa
capslock = esc
esc = capslock

# Remap a to left side Home rows for META, CTRL, Shift, Alt when held
a = overload(control, a)
s = overload(shift, s)

# Alt key
f = overload(alt, f)

# Meta keys
d = overload(meta, d)

# Remap a to right side Home rows for META, CTRL, Shift, Alt when held
; = overload(control, ;)
l = overload(shift, l)

[alt]
l = right
h = left
k = up
j = down
0 = escape

[alt]
space = tab
