[ids]

*

[main]

# REMAPS THE CAPSLOCK KEY TO ESCAPE VISE VISA
capslock = esc
esc = capslock

#==================
# CONTROL KEY
#================== 
f = overload(control, f)
j = overload(control, j)

#==================
# SHIFT KEY
#================== 
d = overload(shift, d)
k = overload(shift, k)

#==================
# META KEY
#================== 
a = overload(meta, a)
; = overload(meta, ;)

#==================
# ALT KEY
#================== 
s = overload(alt, s)
l = overload(alt, l)

[control]
l = right
h = left
k = up
j = down

[alt]
space = tab
0 = escape
b = delete
